### ISSUE TITLE
access token

### ISSUE THREAD

**Issue by dajohi** [exul/matrix-rocketchat#51]
Dec 15 20:59:10.548 INFO Could not process request, the access token `730760afdfdbc5e85935a04e3e6524bb4a7d594f181928d82476b4ab3b7f71b6` did not match any bridged Rocket.Chat server, place: src/matrix-rocketchat/middleware/rocketchat.rs:43 matrix_rocketchat::middleware::rocketchat, version: 0.1.0

Where do I put the token on matrix-rocketchat?

**Comment by exul** [comment]
This is most likely because you did not connect the Rocket.Chat server to the bridge yet. Multiple Rocket.Chat servers can be connected to the bridge. To do so, you have to start a direct chat with the bot user. The user will then give you further instructions on how to connect a Rocket.Chat server.

**Important**: The bridge is still in very early development (as stated in the readme), I don't know anybody who is running it in production. It is very likely that there will be breaking changes (because the Matrix API itself is still in flux).

**Comment by exul** [comment]
@dajohi Was my answer helpful or do you still have problems setting up the bridge?

**Comment by exul** [comment]
Closing this issue becaues of inactivity. Feel free to re-open.
