### ISSUE TITLE
Query: Does the bridge distinguish different users who are talking?

### ISSUE THREAD

**Issue by shawntabrizi** [exul/matrix-rocketchat#72]
The screenshot demo you have shown has two individuals talking to each other through a proxy account on each side. If the chatroom were to contain more than 1 person, on either side, would there be any way to tell them apart from one another?

**Comment by exul** [comment]
Yes, if there are different users on the Matrix side, then each of them will appear as their own user. Rocket.Chat users are always virtual users, no matter if there's one or many, but there's one virtual user per Rocket.Chat user.
The goal of the bridge is, that the people on the Rocket.Chat side should not notice that you're using a bridge. Although currently there are things that don't work properly (and some maybe never will, because it not possible to bridge them). Message editing (currently not supported by Matrix), different allowed formats and sizes, etc.
